# Copyright (C) 2024 Maizil41 https://github.com/maizil41
# https://github.com/ophub/amlogic-s9xxx-openwrt

name: Compile OpenWrt
on:
  workflow_dispatch:
    inputs:
      board_version:
        description: 'Select board version to compile'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - s905d
          - s905w
          - s905w-x96-mini
          - s905x
          - s905x-b860h
          - s905x-nexbox-a95x
          - s905x2
          - s905x3
          - s912
      kernel_version:
        description: 'Select kernel version'
        required: true
        default: '5.15'
        type: choice
        options:
          - 5.10
          - 5.15
          - 5.18
          - 6.0

jobs:
  download:
    name: Download Rootfs
    runs-on: ubuntu-latest
    steps:
      - name: Download Rootfs
        run: |
          pip install gdown
          gdown https://drive.google.com/uc?id=19tQlIYA437ylY1IUaE54s6N8cAqhcgoe
          ROOTFS_PATH=$(find ./ -name "*rootfs.tar.gz")
          echo "ROOTFS_PATH=$ROOTFS_PATH" >> $GITHUB_ENV
          
      - name: Upload Rootfs
        uses: actions/upload-artifact@v3
        with:
          name: amlogic-rootfs
          path: |
            ${{ env.ROOTFS_PATH }}

  build_specific:
    name: Compile Specific Image
    runs-on: ubuntu-22.04
    needs: [download]
    if: github.event.inputs.board_version != 'all'
    strategy:
      matrix:
        board_version: [ "${{ github.event.inputs.board_version }}" ]
    steps:
      - name: Clone Amlogic Builder
        run: |
          if [ -d "amlogic-s9xxx-openwrt" ]; then
            rm -rf amlogic-s9xxx-openwrt
          fi
          git clone --depth 1 https://github.com/maizil41/amlogic-s9xxx-openwrt.git
          cd amlogic-s9xxx-openwrt
          mkdir -p openwrt-armvirt
    
      - name: Download Rootfs
        uses: actions/download-artifact@v3
        with:
          name: amlogic-rootfs
          path: ./amlogic-s9xxx-openwrt/openwrt-armvirt/
          
      - name: Build Firmware ${{ matrix.board_version }} with Kernel ${{ github.event.inputs.kernel_version }}
        run: |
          cd amlogic-s9xxx-openwrt
          sudo ./remake -b ${{ matrix.board_version }} -k ${{ github.event.inputs.kernel_version }} -s 1024
      
      - name: Find Firmware
        run: |
          FILE_PATH=$(find ./amlogic-s9xxx-openwrt/openwrt/out/ -name "*.img.gz")
          echo "FILE_PATH=$FILE_PATH" >> $GITHUB_ENV
          echo -e "FILE_PATH path: $FILE_PATH"
          
      - name: Upload Firmware
        uses: actions/upload-artifact@v3
        with:
          name: amlogic-firmware
          path: |
            ${{ env.FILE_PATH }}

  build_all:
    name: Compile All Images
    runs-on: ubuntu-22.04
    needs: [download]
    if: github.event.inputs.board_version == 'all'
    steps:
      - name: Clone Amlogic Builder
        run: |
          if [ -d "amlogic-s9xxx-openwrt" ]; then
            rm -rf amlogic-s9xxx-openwrt
          fi
          git clone --depth 1 https://github.com/maizil41/amlogic-s9xxx-openwrt.git
          cd amlogic-s9xxx-openwrt
          mkdir -p openwrt-armvirt
    
      - name: Download Rootfs
        uses: actions/download-artifact@v3
        with:
          name: amlogic-rootfs
          path: ./amlogic-s9xxx-openwrt/openwrt-armvirt/
          
      - name: Build All Firmwares with Kernel ${{ github.event.inputs.kernel_version }}
        run: |
          cd amlogic-s9xxx-openwrt
          for board in s905d s905w s905w-x96-mini s905x s905x-b860h s905x-nexbox-a95x s905x2 s905x3 s912; do
            sudo ./remake -b $board -k ${{ github.event.inputs.kernel_version }} -s 1024
          done
      
      - name: Find Firmware
        run: |
          FILE_PATH=$(find ./amlogic-s9xxx-openwrt/openwrt/out/ -name "*.img.gz")
          echo "FILE_PATH=$FILE_PATH" >> $GITHUB_ENV
          echo -e "FILE_PATH path: $FILE_PATH"
          
      - name: Upload Firmware
        uses: actions/upload-artifact@v3
        with:
          name: amlogic-firmware
          path: |
            ${{ env.FILE_PATH }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build_specific, build_all]
    steps:
      - name: Set up date
        id: set_date
        run: |
          export TZ='Asia/Jakarta'
          echo "date_time=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          
      - name: Download Firmware
        uses: actions/download-artifact@v3
        with:
          name: amlogic-firmware
          path: ./artifacts/
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          name: Mutiara-Wrt_23.05.5
          tag_name: v23.05.5_k${{ github.event.inputs.kernel_version }}
          draft: false
          prerelease: false
          files: |
                ./artifacts/*.img.gz
          body: |
            ### Mutiara-Wrt Information
            * Default IP: 192.168.1.1
            * Default username: root
            * Default password: mutiara
            * Default WIFI name: Mutiara-Wrt
            * Default WIFI password: 12345678
            * Release date: ${{ env.date_time }}
            
            ### Tools Installed
            * Radius Monitor
            * OpenClash v0.46.046-beta
            * WhatsApp Bot
            * and others
