name: Auto Commit

on:
  schedule:
    - cron: "0 */4 * * *" # Menjalankan setiap 4 jam
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get current time
        id: current_time
        run: echo "CURRENT_TIME=$(TZ=Asia/Jakarta date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Update update.txt
        run: echo "Last Update : $(date +'%Y-%m-%d %H:%M:%S')" > update.txt

      - name: Commit and Push changes
        run: |
          git config --global user.name "Mutiara-WRT"
          git config --global user.email "mutiara-wrt@users.noreply.github.com"
          git add update.txt
          git commit -m "Auto Commit 🎉 $(date +'%Y-%m-%d %H:%M:%S')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          format: markdown
          message: |
            📢 **Update Notification** 📢
            Last Update: $(date +'%Y-%m-%d %H:%M:%S')
            Repository: ${{ github.repository }}
            Commit Message: Auto Commit $(date +'%Y-%m-%d %H:%M:%S')
