name: Auto Commit

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get current time
        id: current_time
        run: echo "CURRENT_TIME=$(TZ=Asia/Jakarta date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Update update.txt
        run: |
          echo "Last Update : ${{ env.CURRENT_TIME }}" > update.txt

      - name: Commit and Push changes
        run: |
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"
          git add update.txt
          git commit -m "Auto Commit 🎉 ${{ env.CURRENT_TIME }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
