name: Build OpenWrt

on:
  workflow_dispatch:

jobs:
  make_rootfs:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt update -y > /dev/null 2>&1
        sudo apt install net-tools make gawk git curl unzip bzip2 -y > /dev/null 2>&1
        sudo apt install -y $(curl -fsSL https://is.gd/depend_ubuntu2204_openwrt) > /dev/null 2>&1

    - name: Download Image Builder
      run: |
        wget https://downloads.openwrt.org/releases/23.05.5/targets/armsr/armv8/openwrt-imagebuilder-23.05.5-armsr-armv8.Linux-x86_64.tar.xz > /dev/null 2>&1
        tar -J -x -f openwrt-imagebuilder-23.05.5-armsr-armv8.Linux-x86_64.tar.xz > /dev/null 2>&1

    - name: Build Rootfs
      run: |
        cd openwrt-imagebuilder-23.05.5-armsr-armv8.Linux-x86_64 > /dev/null 2>&1
        make image PROFILE="generic" PACKAGES=" \
        -dnsmasq -luci-theme-bootstrap \
        dnsmasq-full cgi-io libiwinfo libiwinfo-data libiwinfo-lua liblua liblucihttp liblucihttp-lua \
        " FILES="files" > /dev/null 2>&1 || true
        
    - name: Extract Rootfs
      run:
        echo -e "Current Path"
        pwd
        echo -e "List Files"
        ls -la
