name: Download Image Builder

on:
  workflow_dispatch:

jobs:
  make_rootfs:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download Image Builder
      run: |
        wget https://downloads.openwrt.org/releases/23.05.5/targets/armsr/armv8/openwrt-imagebuilder-23.05.5-armsr-armv8.Linux-x86_64.tar.xz > /dev/null 2>&1
        
    - name: Extract Image Builder
      run:
        mkdir -p Builder > /dev/null 2>&1
        tar -xf openwrt-imagebuilder-23.05.5-armsr-armv8.Linux-x86_64.tar.gz -C Builder --strip-components=1 > /dev/null 2>&1
        rm -rf  openwrt-imagebuilder-23.05.5-armsr-armv8.Linux-x86_64.tar.gz > /dev/null 2>&1

    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "initial commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
