name: Compile OpenWrt
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        board_version: [h96-max-m2, nanopi-r5c, nanopi-r5s, orangepi-5-plus, rk3318-box, s905-beelink-mini, s905-mxqpro-plus, s905d, s905w, s905w-w95, s905w-x96-mini, s905w-x96w, s905x, s905x-b860h, s905x-nexbox-a95x, s905x-t95, s905x-tbee, s905x-tx9, s905x2, s905x2-x96max-2g, s905x3, s905x3-a95xf3, s905x3-a95xf3-gb, s905x3-b, s905x3-h96max, s905x3-hk1, s905x3-tx3, s905x3-tx3-bz, s905x3-x96air, s905x3-x96air-gb, s905x3-x96max, s912, s912-h96pro-plus, s912-nexbox-a1, s912-nexbox-a2, s912-phicomm-t1, tanix-tx6]

    steps:
      - name: Set Timezone
        run: |
          echo "Setting timezone to Asia/Jakarta"
          sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
          sudo dpkg-reconfigure -f noninteractive tzdata
    
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Depedency
        run: |
          sudo -E apt-get update > /dev/null 2>&1
          sudo -E apt install net-tools make gawk git curl unzip bzip2 > /dev/null 2>&1
          sudo -E apt install -y $(curl -fsSL https://is.gd/depend_ubuntu2204_openwrt) > /dev/null 2>&1

      - name: Clone Amlogic Builder
        run: |
          if [ -d "amlogic-s9xxx-openwrt" ]; then
            rm -rf amlogic-s9xxx-openwrt
          fi

          git clone --depth 1 https://github.com/ophub/amlogic-s9xxx-openwrt.git
          cd amlogic-s9xxx-openwrt
          mkdir -p openwrt-armvirt

      - name: Download Rootfs
        run: |
          wget "https://drive.usercontent.google.com/download?id=1ceuwLfkoLYe9vsrPr4Drkm6NnRda7rNK&export=download&authuser=0&confirm=t&uuid=871ff001-b8a2-4e57-a907-4d0c7863b0a5&at=AN_67v29Ax98UGn2IR61HVxBPtUA%3A1729447274347" -O amlogic-s9xxx-openwrt/openwrt-armvirt/Mutiara-Wrt_23.05.5_rootfs.tar.gz 

      - name: Build Firmware ${{ matrix.board_version }}
        run: |
          cd amlogic-s9xxx-openwrt
          sudo ./remake -b ${{ matrix.board_version }} -k 5.15 -s 1024

      - name: Find Firmware
        run: |
          FILE_PATH=$(find ./amlogic-s9xxx-openwrt/openwrt/out/ -name "*.img.gz")
          echo "FILE_PATH=$FILE_PATH" >> $GITHUB_ENV
          echo -e "FILE_PATH path: $FILE_PATH"
          
      - name: Upload Firmware
        uses: actions/upload-artifact@v3
        with:
          name: amlogic-firmware
          path: |
            ${{ env.FILE_PATH }}
            
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: Set up date
        id: set_date
        run: |
          export TZ='Asia/Jakarta'
          echo "date_time=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          
      - name: Download Firmware
        uses: actions/download-artifact@v3
        with:
          name: amlogic-firmware
          path: ./artifacts/
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          name: Mutiara-Wrt_23.05.5
          tag_name: v23.05.5
          draft: false
          prerelease: false
          files: |
                ./artifacts/*.img.gz
          body: |
            ### Mutiara-Wrt Information
            * Default IP: 192.168.1.1
            * Default username: root
            * Default password: mutiara
            * Default WIFI name: Mutiara-Wrt
            * Default WIFI password: 12345678
            * Release date: ${{ env.date_time }}
            
            ### Tools Installed
            * Radius Monitor
            * OpenClash v0.46.046-beta
            * WhatsApp Bot
            * and others
