name: Build OpenWRT X86-64

on:
  workflow_dispatch:

jobs:
  make_rootfs:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt update -y > /dev/null 2>&1
        sudo apt install net-tools make gawk git curl unzip bzip2 -y > /dev/null 2>&1
        sudo apt install -y $(curl -fsSL https://is.gd/depend_ubuntu2204_openwrt) > /dev/null 2>&1

    - name: Download OpenWRT Image Builder
      run: |
        wget https://downloads.openwrt.org/releases/23.05.5/targets/x86/64/openwrt-imagebuilder-23.05.5-x86-64.Linux-x86_64.tar.xz > /dev/null 2>&1
        tar -J -x -f *.tar.xz > /dev/null 2>&1

    - name: Build OpenWRT Image
      run: |
        cd openwrt-imagebuilder-23.05.5-x86-64.Linux-x86_64 > /dev/null 2>&1
        make image PROFILE="generic" PACKAGES=" \
        cgi-io libiwinfo libiwinfo-data libiwinfo-lua liblua liblucihttp liblucihttp-lua \
        libubus-lua lua luci luci-app-firewall luci-app-opkg luci-base luci-lib-base \
        luci-lib-ip luci-lib-jsonc luci-lib-nixio luci-mod-admin-full luci-mod-network \
        luci-mod-status luci-mod-system luci-proto-ipv6 luci-proto-ppp luci-ssl \
        luci-theme-bootstrap rpcd rpcd-mod-file rpcd-mod-iwinfo rpcd-mod-luci \
        rpcd-mod-rrdns uhttpd uhttpd-mod-ubus luci-compat \
        ath9k-htc-firmware btrfs-progs hostapd hostapd-utils kmod-ath kmod-ath9k kmod-ath9k-common \
        kmod-ath9k-htc kmod-cfg80211 kmod-crypto-acompress kmod-crypto-crc32c kmod-crypto-hash \
        kmod-fs-btrfs kmod-mac80211 wireless-tools wpa-cli wpa-supplicant \
        libc php8 php8-cgi php8-mod-session php8-mod-ctype php8-mod-fileinfo php8-mod-zip php8-mod-iconv php8-mod-mbstring \
        zoneinfo-core zoneinfo-asia nano htop unzip wget wget-ssl libmbedtls tar bash luci-app-mwan3 luci-theme-material \
        netdata httping coreutils-timeout kmod-usb-net-rndis iperf3 \
        usbutils kmod-usb-net-cdc-ether usb-modeswitch \
        kmod-pcengines-apuv2 beep kmod-leds-gpio kmod-crypto-hw-ccp kmod-usb-core kmod-usb-ohci kmod-usb2 kmod-usb3 kmod-sound-core kmod-pcspkr amd64-microcode flashrom irqbalance fstrim curl \
        ath10k-firmware-qca988x kmod-ath10k \
        qmi-utils kmod-usb-net-qmi-wwan libqmi luci-proto-qmi uqmi \
        " FILES="files" > /dev/null 2>&1 || true

    - name: Find Firmware
      run: |
        FILE_PATH=$(find -name "*.img.gz")
        echo "FILE_PATH=$FILE_PATH" >> $GITHUB_ENV
        echo -e "FILE_PATH path: $FILE_PATH"

    - name: Upload Firmware
      uses: actions/upload-artifact@v3
      with:
        name: openwrt-firmware
        path: |
            ${{ env.FILE_PATH }}
