name: Compile OpenWrt
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        board_version: [a311d, beikeyun, chainedbox, crrc, dg3399, dlfr100, e20c, e25, eaidk-610, emb3531, fine3399, firefly-rk3399, jp-tvbox, h28k, h66k, h68k, h69k, h88k, h88k-v3, h96-max-m2, hs530r, hugsun-x99, ipc-r, king3399, kylin3399, lckfb-tspi, leez, lx-r3s, mrkaio-m68s, nanopc-t6, nanopi-r5c, nanopi-r5s, orangepi-5-plus, panther-x2, r66s, r68s, renegade-rk3328, rk3318-box, rock5b, rock5c, ruisen-box, s905, s905-beelink-mini, s905-mxqpro-plus, s905d, s905d-ki-pro, s905d-sml5442tw, s905l, s905l-aurora-1s, s905l-b860av21u, s905l-mg101, s905l2, s905l2-e900v21e, s905l2-wojia, s905l3, s905l3-cm211, s905l3-unt400g1, s905l3-unt402a, s905l3a, s905l3a-cm311, s905l3a-m401a, s905l3b, s905l3b-e900v21d, s905l3b-e900v22d, s905l3b-e900v22e, s905l3b-ip103h, s905l3b-rg020et-ca, s905l3b-unt403a, s905lb-ipbs9505, s905lb-q96-mini, s905lb-r3300l, s905mb, s905w, s905w-w95, s905w-x96-mini, s905w-x96w, s905x, s905x-b860h, s905x-nexbox-a95x, s905x-t95, s905x-tbee, s905x-tx9, s905x2, s905x2-km3, s905x2-x96max-2g, s905x3, s905x3-2101, s905x3-a100, s905x3-a95xf3, s905x3-a95xf3-gb, s905x3-b, s905x3-h96max, s905x3-hk1, s905x3-ip1001m, s905x3-q1, s905x3-q2, s905x3-tx3, s905x3-tx3-bz, s905x3-ugoosx3, s905x3-whale, s905x3-x88-pro-x3, s905x3-x96air, s905x3-x96air-gb, s905x3-x96max, s912, s912-h96pro-plus, s912-m8s-pro, s912-nexbox-a1, s912-nexbox-a2, s912-onecloudpro, s912-phicomm-t1, s912-t95z-plus, s912-tx8-max, s912-tx9-pro-2g, s912-tx9-pro-3g, s912-x92, s912-zyxq-fake, s922x, s922x-ct2000, s922x-gtking, s922x-gtkingpro-h, s922x-odroid-n2, s922x-reva, s922x-ugoos-am6, seewo-sv21, smart-am40, station-m1, swan1-w28, sw799, tanix-tx6, tb-ls3399, tn3399, tpm312, tqc-a01, tvi3315a, vplus, xiaobao, zcube1-max, zk-r39a, zysj]

    steps:
      - name: Set Timezone
        run: |
          echo "Setting timezone to Asia/Jakarta"
          sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
          sudo dpkg-reconfigure -f noninteractive tzdata
    
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone Amlogic Builder
        run: |
          if [ -d "amlogic-s9xxx-openwrt" ]; then
            rm -rf amlogic-s9xxx-openwrt
          fi

          git clone --depth 1 https://github.com/ophub/amlogic-s9xxx-openwrt.git
          cd amlogic-s9xxx-openwrt
          mkdir -p openwrt-armvirt

      - name: Download Rootfs
        run: |
          wget "https://drive.usercontent.google.com/download?id=1ceuwLfkoLYe9vsrPr4Drkm6NnRda7rNK&export=download&authuser=0&confirm=t&uuid=871ff001-b8a2-4e57-a907-4d0c7863b0a5&at=AN_67v29Ax98UGn2IR61HVxBPtUA%3A1729447274347" -O amlogic-s9xxx-openwrt/openwrt-armvirt/Mutiara-Wrt_23.05.5_rootfs.tar.gz 

      - name: Build Firmware ${{ matrix.board_version }}
        run: |
          cd amlogic-s9xxx-openwrt
          sudo ./remake -b ${{ matrix.board_version }} -k 5.15 -s 1024

      - name: Find Firmware
        run: |
          FILE_PATH=$(find ./amlogic-s9xxx-openwrt -name "{{ matrix.board_version }}*.img.gz")
          echo "FILE_PATH=$FILE_PATH" >> $GITHUB_ENV
          echo -e "FILE_PATH path: $FILE_PATH"
          
      - name: Upload Firmware
        uses: actions/upload-artifact@v3
        with:
          name: amlogic-firmware
          path: |
            ${{ env.FILE_PATH }}
            
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: Set up date
        id: set_date
        run: |
          export TZ='Asia/Jakarta'
          echo "date_time=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          
      - name: Download Firmware
        uses: actions/download-artifact@v3
        with:
          name: amlogic-firmware
          path: ./artifacts/
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          name: Mutiara-Wrt_23.05.5
          tag_name: v23.05.5
          draft: false
          prerelease: false
          files: |
                ./artifacts/*.img.gz
          body: |
            ### Mutiara-Wrt Information
            - Default IP: 192.168.1.1
            - Default username: root
            - Default password: mutiara
            - Default WIFI name: Mutiara-Wrt
            - Default WIFI password: 12345678
            - Release date: ${{ env.date_time }}
